apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: registry.k8s.io/kwok/kwok
    newTag: v0.1.0

commonLabels:
  app: kwok-controller

namespace: kube-system

resources:
  - kwok-deployment.yaml
  - kwok-serviceaccount.yaml
  - kwok-clusterrole.yaml
  - kwok-clusterrolebinding.yaml
